{{/*apiVersion: extensions/v1beta1*/}}
{{/*kind: Ingress*/}}
{{/*metadata:*/}}
{{/*  name: {{.Release.Name}}*/}}
{{/*  annotations:*/}}
{{/*    kubernetes.io/ingress.class: {{.Values.ingressClass}}*/}}
{{/*    nginx.ingress.kubernetes.io/proxy-body-size: 8m*/}}
{{/*    nginx.ingress.kubernetes.io/proxy-buffering: "on"*/}}
{{/*    nginx.ingress.kubernetes.io/server-snippet: |*/}}
{{/*      proxy_cache mycache;*/}}
{{/*      proxy_cache_lock on;*/}}
{{/*      proxy_cache_valid any 60m;*/}}
{{/*      proxy_ignore_headers Cache-Control;*/}}
{{/*      add_header X-Cache-Status $upstream_cache_status;*/}}
{{/*spec:*/}}
{{/*  rules:*/}}
{{/*    - http:*/}}
{{/*        paths:*/}}
{{/*          - backend:*/}}
{{/*              serviceName: speedtest*/}}
{{/*              servicePort: 80*/}}
{{/*            pathType: ImplementationSpecific*/}}
{{/*            path: /speedtest*/}}
